version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    command: scripts/start_services.sh
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    command: scripts/start_services.sh backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
