services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: cc-backend
    command: bash -c "chmod +x scripts/*.sh && scripts/start_services.sh backend"
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: cc-db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
