# Generated by Django 4.2.1 on 2023-06-03 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos numéricos.', regex='^\\d+$')], verbose_name='telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos numéricos.', regex='^\\d+$')], verbose_name='telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
