# Generated by Django 4.2.1 on 2023-06-06 14:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleproduct_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], unique=True, verbose_name='Dia da semana')),
                ('min_value', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('0.100'))], verbose_name='Comissão mínima')),
                ('max_value', models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('0.100'))], verbose_name='Comissão máxima')),
            ],
            options={
                'verbose_name': 'limites de taxa de comissão',
                'verbose_name_plural': 'limites de taxa de comissão',
                'ordering': ['weekday'],
            },
        ),
    ]
