# Generated by Django 4.2.1 on 2023-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_commissionratelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionratelimit',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], unique=True, verbose_name='Dia da semana'),
        ),
    ]
