# Generated by Django 4.2.1 on 2023-06-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_commission_rate'),
        ('sales', '0004_alter_commissionratelimit_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'ordering': ['-id'], 'verbose_name': 'produtos e vendas', 'verbose_name_plural': 'produtos e vendas'},
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale', verbose_name='venda'),
        ),
    ]
